version: "3.9"

networks:
 snack-shop-network:
  driver: bridge

services:
 snack-shop-mysql:
  image: mysql:8.0
  environment:
   MYSQL_ROOT_PASSWORD: 12345678
  ports:
   - 3306:3306
  networks:
   - snack-shop-network
  healthcheck:
   test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
   timeout: 20s
   retries: 10

 snack-shop-api:
  build:
   context: .
   dockerfile: Dockerfile
  environment:
   DB_HOST: snack-shop-mysql
  ports:
   - 9000:9000
  networks:
   - snack-shop-network
  depends_on:
   snack-shop-mysql:
    condition: service_healthy