apiVersion: v1
kind: Service
metadata:
  name: snack-shop-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: snack-shop-mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snack-shop-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snack-shop-mysql
  template:
    metadata:
      labels:
        app: snack-shop-mysql
    spec:
      containers:
        - name: snack-shop-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"
          ports:
            - containerPort: 3306