name: CI/CD Pipeline
on:
  push:
    branches:
      - main-terraform
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test with Maven
        run: mvn test

      - name: Build Complete
        run: echo "Build Complete"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: snackshop-repository
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name snackshop-cluster --region us-west-2

      - name: Replace AWS_ACCOUNT_ID in k8s/01-snack-shop-api.yml
        run: |
          sed -i "s|\${AWS_ACCOUNT_ID}|${{ secrets.AWS_ACCOUNT_ID }}|" k8s/01-snack-shop-api.yml

#      - name: Replace DB_NAME in k8s/01-snack-shop-api.yml
#        run: |
#          sed -i "s|snack-shop-mysql|${{ secrets.DB_ENDPOINT }}|" k8s/01-snack-shop-api.yml

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/01-snack-shop-api.yml
          kubectl apply -f k8s/02-hpa.yml
#          kubectl apply -f k8s/00-snack-shop-mysql.yml
#          kubectl apply -f k8s/03-load-balancer.yml

      - name: Deploy Complete
        run: echo "Deploy Complete"